### ISSUE TITLE
the instructions for pip installation are incomplete.

### ISSUE THREAD

**Issue by schetudiante** [schuetzgroup/sdt-python#3]
hey team sdt-python,
I run python on a server and would like to install sdt-python using because of permission issues.

Kindly guide, thanks :)

**Comment by lschr** [comment]
Hey, could you provide some specifics, such as what you were doing, what went wrong, error messages, etc?

**Comment by schetudiante** [comment]
I do not have server privileges to install conda. 
so I need help to install sdt-python with the pip .. 
but the main readme does not mention how this can be done

**Comment by lschr** [comment]
Have you followed the [instructions given in the README](https://github.com/schuetzgroup/sdt-python/blob/master/README.rst#using-pip-untested)? If yes, what error did you encounter?
Btw., you don't need elevated privileges to install Anaconda/miniconda.

**Comment by schetudiante** [comment]
> Have you followed the [instructions given in the README](https://github.com/schuetzgroup/sdt-python/blob/master/README.rst#using-pip-untested)? If yes, what error did you encounter?
No, because it only mentions the command `python -m pip install .` but does not provide the source code as it says.
(see image)
![image](https://user-images.githubusercontent.com/82269015/116379023-ed5b6680-a812-11eb-9007-d8268e5ae8b8.png)


> Btw., you don't need elevated privileges to install Anaconda/miniconda.
As far as I know one needs to install the .sh file for which I don't have the server privileges :)
the pip method would be great to use, thanks

**Comment by lschr** [comment]
> > Have you followed the [instructions given in the README](https://github.com/schuetzgroup/sdt-python/blob/master/README.rst#using-pip-untested)? If yes, what error did you encounter?

> It only mentions the command `python -m pip install .` but does not provide the source code as it says.

The code is here on Github. You can clone it using git or download from the release page.

> > Btw., you don't need elevated privileges to install Anaconda/miniconda.

> As far as I know one needs to install the .sh file for which I don't have the server privileges :)

If you have shell access, you should be able execute the .sh file. Anaconda can (should) be installed in the home directory.

**Comment by schetudiante** [comment]
Thank you for taking time to reply to my query.

bests :)
