### ISSUE TITLE
sdt.changepoint.BayesOnline uses student-t distribution wich is not a Exponential family likelihood

### ISSUE THREAD

**Issue by smh87** [schuetzgroup/sdt-python#4]
In the paper  "Bayesian Online Changepoint Detection" written by Ryan P. Adams in 2007 the online change point detection uses Exponential family likelihoods . in 
class sdt.changepoint.BayesOnline(hazard='const', obs_likelihood='student_t', hazard_params={'time_scale': 250.0}, obs_params={'alpha': 0.1, 'beta': 0.01, 'kappa': 1.0, 'mu': 0.0}, engine='numba')

the observation likelihood is set to student-t distribution, student-t distribution cannot be a exponential family regarding https://stats.stackexchange.com/questions/444468/is-the-t-distribution-a-member-of-the-exponential-family and https://en.wikipedia.org/wiki/Exponential_family#Table_of_distributions
Please use another probability distribution

**Comment by lschr** [comment]
Hey, first I have to admit that I have little knowledge about the statistics behind this algorithm. However, when looking at
https://github.com/hildensia/bayesian_changepoint_detection/blob/2ba96fd8556e0ab05c395bd5cbaaa5e5c335318f/bayesian_changepoint_detection/online_changepoint_detection.py#L76-L78
which the implementation here is based on, it seems like the student-t likelihood implies Gaussian distribution of data, which is an exponential family distribution. Can you comment on this?

**Comment by lschr** [comment]
Closing due to lack of response.
