### ISSUE TITLE
AttributeError: module 'lmfit.models' has no attribute 'COMMON_DOC'

### ISSUE THREAD

**Issue by pulga10** [schuetzgroup/sdt-python#5]
Hi,

When calling `optimize.Gaussian2DModel()` im getting an error like the title says, i.e. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.9/site-packages/sdt/optimize/gaussian_fit.py", line 131, in __init__
    """Constructor""" + lmfit.models.COMMON_DOC
AttributeError: module 'lmfit.models' has no attribute 'COMMON_DOC
```

I'm using sdt 17.1. and lmfit 1.0.3.

**Comment by lschr** [comment]
Thanks for the report. `COMMON_DOC` was removed somewhere between `lmfit` releases 1.0.2 and 1.0.3 (see lmfit/lmfit-py@aa0e22873ab24b6e7085f625d9c7f88c1979b8a8). I fixed `sdt`'s usage of `COMMON_DOC` in 78d16996037759ac476729e95d385a2b1d2636a5. Until a new version of `sdt` is released, you can work around the issue by downgrading `lmfit` to 1.0.2.
