### ISSUE TITLE
Pypi artifact of sdt-python

### ISSUE THREAD

**Issue by AnandInguva** [schuetzgroup/sdt-python#6]
Hi,

Is there a plan to make this package available through pypi?

**Comment by lschr** [comment]
I have no plans to do. First, I cannot test this since I am exclusively using anaconda/conda-forge. Second, I have very little time. Would you like to step in?

**Comment by lschr** [comment]
Closing due to lack of response.

**Comment by lschr** [comment]
The package (v19.0.0) is now available on PyPI.
